### ISSUE TITLE
Upload method

### ISSUE THREAD

**Issue by RZulfikri** [Vydia/react-native-background-upload#1]
hi i want ask something, what method used in this upload scheme.? is it only and default using POST method.? how if i want use PUT method.?

thanks.

**Comment by StevePotter** [comment]
Hi, currently POST is hardcoded.  This could be fixed rather easily:
Change POST to something else: https://github.com/Vydia/react-native-background-upload/blob/master/ios/VydiaRNFileUploader.m#L107

Add setMethod to: https://github.com/Vydia/react-native-background-upload/blob/master/android/src/main/java/com/vydia/UploaderModule.java#L113

If I add the feature, will you be willing to test it for me?

**Comment by RZulfikri** [comment]
@StevePotter  yes of couse thanks.

**Comment by StevePotter** [comment]
@RZulfikri great I'll get it done soon

**Comment by StevePotter** [comment]
@RZulfikri it's done in version 0.1
