### ISSUE TITLE
TypeError: Cannot read property 'startUpload' of undefined

### ISSUE THREAD

**Issue by halaharr** [Vydia/react-native-background-upload#104]
Hi,
    I am getting this error the following error trying to use this plugin.
TypeError: Cannot read property 'startUpload' of undefined

I am using version 5.0.0 and RN version 0.55.1.

Also when I have ESLint errors:
"Caution: 'Upload ' also has need export startup. 

I tried declaring startup 
import Upload, { startUpload } from 'react-native-background-upload';

but does not work. 

Thanks for your help.

**Comment by TSMMark** [comment]
```
import Upload, { startUpload } from 'react-native-background-upload'
startUpload()
```

is different from 

```
import Upload from 'react-native-background-upload'
Upload.startUpload()
```

Please follow the readme https://github.com/Vydia/react-native-background-upload#usage

**Comment by mephisto83** [comment]
I'm getting a similar error.
"react-native": "0.57.8",

import Upload from 'react-native-background-upload'

TypeError: Cannot read property 'startUpload' of undefined
    at Object.startUpload (index.js:77)
    at Object.upload (uploadservice.js:27)
    at #######.js:2803
    at #######.js:2730
    at run (es6.promise.js:87)
    at es6.promise.js:100
    at flush (_microtask.js:18)
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:295
