### ISSUE TITLE
Project uses unavailable Gradle version

### ISSUE THREAD

**Issue by asutula** [Vydia/react-native-background-upload#114]
Looks like Google unpublished Gradle 2.x from all the repos, so this project now fails to build.

**Comment by asutula** [comment]
Nice temporary work around. Thanks @ahaus

**Comment by andorfermichael** [comment]
same problem here:

> Configure project :react-native-background-upload
Project is either no Android app project or build version has not been set to override

FAILURE: Build failed with an exception.

```
* What went wrong:
A problem occurred configuring project ':react-native-background-upload'.
> Could not resolve all artifacts for configuration ':react-native-background-upload:classpath'.
   > Could not find com.android.tools.build:gradle:2.3.3.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
       - https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
     Required by:
         project :react-native-background-upload
```

**Comment by TSMMark** [comment]
Hey anyone interested in contributing a PR?

**Comment by ahaus** [comment]
Maybe this is only a temporary problem and they will republish Gradle 2.x stuff.

**Comment by ahaus** [comment]
Did not check. I am still sticking to the workaround.

**Comment by StevePotter** [comment]
Just tested on https://github.com/Vydia/ReactNativeBackgroundUploadExample and it works now.  Must have been a temporary outage.  I'm closing the issue as a result.  If something is still wrong, please let me know
