### ISSUE TITLE
[iOS] [Debug] App crashing as soon as upload starts

### ISSUE THREAD

**Issue by BaderSerhan** [Vydia/react-native-background-upload#122]
I'm getting the following error as soon as I try uploading something in debug mode:

***Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You must override the `supportedEvents` method of fir_0x600000393c00_VydiaRNFileUploader'***

In release mode, it is working just fine!

I looked in the class, and the `supportedEvents` method seems to be overrode. 

Here's the supportedEvents method:
```javascript
 - (NSArray<NSString *> *)supportedEvents {
    return @[
        @"RNFileUploader-progress",
        @"RNFileUploader-error",
        @"RNFileUploader-cancelled",
        @"RNFileUploader-completed"
    ];
}
```
And here's where the crash is happening in XCode:
`_urlSession = [NSURLSession sessionWithConfiguration:sessionConfiguration delegate:self delegateQueue:nil];`

**Comment by TSMMark** [comment]
Thanks for the report. Are you able to reproduce the issue in a fork of the RNBU example app?

**Comment by berkcoker** [comment]
I've noticed that this only happens on Debug mode, but is fine on Release

**Comment by alexivison** [comment]
I'm also having the same problem... Any movement on this ?

**Comment by BaderSerhan** [comment]
@TSMMark I tried it on the RNBU example app, and it is working fine. I think it is a conflict with `react-native-firebase` because this issue started appearing when I integrated `Firebase`. It is affecting all of my logic and now the app is nearly non-functional because of this :/.

@berkcoker @alexivison  Can you confirm if you have firebase integrated?

**Comment by BaderSerhan** [comment]
any update on this? This is crucial to my app and if it doesn't work out I'll have to switch to another component :(

**Comment by BaderSerhan** [comment]
I just removed `Firebase/Performance` from the `pods`

    Removing FirebaseABTesting
    Removing FirebasePerformance
    Removing FirebaseRemoteConfig
    Removing GoogleToolboxForMac

And the crash stops! I don't know which one exactly was causing the conflict, but I think this solves it for now and we can move on with our lives.

**Comment by TSMMark** [comment]
Glad to hear that @BaderSerhan! Thanks for update

**Comment by Shervanator** [comment]
I'm still having this issue in Debug mode, did anyone have any clues/ideas? Other projects have also had this issue: https://github.com/WebEngage/react-native-webengage/issues/1

**Comment by BaderSerhan** [comment]
@Shervanator Do you have firebase integrated? Because it seems to be an issue with the method `swizzling`. Try removing `Firebase/Performance` and see if it persists.

**Comment by Shervanator** [comment]
yep! firebase performance analytics is definitely causing the issues. I have removed it for the moment, but it is a super common library, so it would be cool to figure out why its not working as well!

**Comment by pribeh** [comment]
same here. removing firebase performance resolves the issue

**Comment by Jarred-Sumner** [comment]
```
[FIRPerformance sharedInstance].dataCollectionEnabled = false;
[FIRPerformance sharedInstance].instrumentationEnabled = false;
```

This will disable it if you don't want to remove it just yet. Can stick that code into your AppDelegate.

**Comment by LeoW93** [comment]
This is still an issue it seems, but @Jarred-Sumner 's fix works nicely - thanks for that!
You can even do:
```objective-c
#if DEBUG
  [FIRPerformance sharedInstance].dataCollectionEnabled = false;
  [FIRPerformance sharedInstance].instrumentationEnabled = false;
#endif
```
so that you don't lose the firebase performance tools for release mode :)
