### ISSUE TITLE
Support for Android 9.0 Pie

### ISSUE THREAD

**Issue by gotev** [Vydia/react-native-background-upload#123]
Hi there! This is just to let you know new version 3.5.0 of Android Upload Service has been published, with support for latest Android 9, OkHttp 3.12.1 and Google AndroidX libraries: https://github.com/gotev/android-upload-service/releases/tag/3.5.0

**Comment by StevePotter** [comment]
Thanks @gotev!  I already started the upgrade in PR #125

**Comment by phsumi** [comment]
@StevePotter did you encounter any dragons on this one? i'm just starting with a project, so jumping on the latest and greatest upload service would be the logical choice for me :)

**Comment by StevePotter** [comment]
@phsumi I am having a heck of a time upgrading the background uploader.  The background upload service upgrades to androidx, which affects a ton of stuff and I couldn't even compile the sample application.  How's your Android skills?  Would you be willing to help solve this issue?  

@gotev I am really struggling with AndroidX, which I believe doesn't work with React Native yet.  See https://github.com/facebook/react-native/issues/23112
Is there anything you know of that I can try?  Any help would be appreciated.  I can give exact instructions for setting up the example app if you're willing to take a look at it.  Thanks!

**Comment by phsumi** [comment]
@stephenpotter yeah, I ran into the same issues. Unfortunately, I don’t have any experience in native development at this point, so I wouldn’t even know where to start :/




________________________________

**Comment by gotev** [comment]
@StevePotter I'm not using RN, as I keep on making fully native iOS and Android apps. AndroidX is the present and future of Android so RN should support it. All the official and most of third party native libraries are already on AndroidX. To ease native apps transitioning, Google has made the "jetifier" which tries to automatically translate old support libraries to the new AndroidX packages when compiling. This requires that your project is set up for AndroidX. In a fully native existing project, to do so it's sufficient to open it with Android Studio and run the "Migrate to AndroidX.." automatic tool. It cares to setup Gradle, enable the jetifier and to change all the imports with the new ones. It has worked pretty well for all of my projects. Try that first. If some other errors arise, then they will surely be in the RN binding layer.

**Comment by shivam4ukhandelwal** [comment]
Hi how to upgrade and fix this AndroidX issue on React-Native

**Comment by paruckerr** [comment]
```
react-native-background-upload/android/src/main/java/com/vydia/UploaderModule.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/Eduardo/Develop/mission/missionbrasil/node_modules/react-native-background-upload/android/src/main/java/com/vydia/UploaderModule.java:52: error: cannot find symbol
  private void sendEvent(String eventName, @Nullable WritableMap params) {
                                            ^
  symbol:   class Nullable
  location: class UploaderModule
```
Someone have this issue too? This happen after I set this params in gradle.properties

```
android.useAndroidX=true
android.enableJetifier=true
```

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 342.33 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6
      react-native: ^0.59.9 => 0.59.9
```

**Comment by anilios** [comment]
facing same issue...
![Screenshot 2019-06-19 at 5 25 34 PM](https://user-images.githubusercontent.com/694814/59763469-4b35d380-92b7-11e9-8cb1-176642378cf5.png)

**Comment by swiety85** [comment]
Exchange it with `import androidx.annotation.Nullable;` inside the npm module.
Additionally, you should apply the changes from #125.
Off course you should not disable notification for Android 9, because it's forced to have the notification for this version of Android. Therefore the following config will not work:
```js
const options = {
  url: 'https://myservice.com/path/to/post',
  path: 'file://path/to/file/on/device',
  method: 'POST',
  // ...
  // Below are options only supported on Android
  notification: {
    enabled: false
  }
}
```
Personally I just remove `notification` entry.

Good luck! :)

PS. @gotev When related PR will be merged?

**Comment by gotev** [comment]
@swiety85 which PR?

**Comment by swiety85** [comment]
Sorry, the question about PR #125 merging time is for @StevePotter.
I think exchanging dep to `import androidx.annotation.Nullable;` in UploaderModule.java should be good enough to merge the #125. I tested these changes in my project and it works without any issues.
