### ISSUE TITLE
upload a file in "Body" request

### ISSUE THREAD

**Issue by mlop113** [Vydia/react-native-background-upload#126]
Like this, but I don't know what to do
![screen shot 2019-01-23 at 12 23 32](https://user-images.githubusercontent.com/22517602/51584857-b72f2e00-1f09-11e9-804e-3f24782a7291.png)

**Comment by TSMMark** [comment]
https://github.com/Vydia/ReactNativeBackgroundUploadExample/issues/10#issuecomment-456832903
