### ISSUE TITLE
Event listener 'completed' not being called (random)

### ISSUE THREAD

**Issue by pedrosimao** [Vydia/react-native-background-upload#129]
On my application the event 'completed' sometimes is not called when upload finishes. I have tried to find the culprit but I was not able to reproduce the bug every time. It's really strange. This can happen even if the application is open all the time (not on background).

I currently dispatch a redux action inside the completed event, this action is responsible for deleting the upload progress bar from inside the app. The result of the event not being called is the progress bar never goes away.

Also, I don't understand how this redux action could be dispatched in case the application gets closed. If it is not possible, then I would have to verify my AppState change, I guess. But how could I get a confirmation that upload was really finished if app is closed during the upload?

**Comment by StevePotter** [comment]
@pedrosimao thanks for writing.  Is this iOS or Android?  Ideally you could get a breakpoint set in the native code, which is very easy to do in either xcode or android studio.  This bug seems to be affecting others and I'd like to get to the bottom of it.  We should first determine whether it's native or JS.  Any help you can do as far as debugging goes would be really appreciated.  Unfortunately this library can be difficult to troubleshoot.

**Comment by pedrosimao** [comment]
@StevePotter I have noticed this happens mainly with Android when I am using cell network (3G/4G). I think it happens less when I am using WiFi network. It seems that the callback of `Upload.startUpload()` will not listen to any events (progress, error, cancelled or completed). I still have no perfect way to reproduce it, but investigating it on Android with bad 3G network might be a good way to go.

**Comment by pedrosimao** [comment]
I also noticed that JS code inside catch is not called either. The error happens even when the app is never put on the background. Basically, I have wrapped the startUpload function inside a Promise, then I call this Promise / Function from another method inside a `try/catch`. I realized that when the bug happens no code after the `await` (inside try) is executed, nor what is inside my catch. Here is how I have created my Promise:
```
const uploadFiles = async (url, pathFile, inspection, dispatch) =>
  new Promise((resolve, reject) => {
    Upload.startUpload({
      url,
      path: pathFile,
      method: 'PUT',
      type: 'raw',
      headers: {
        'content-type': 'multipart/form-data',
      },
      // Below are options only supported on Android
      notification: {
        enabled: true,
      },
    })
      .then(uploadId => {
        dispatch(setUploadingProgress({ cancelId: uploadId, inspectionId: inspection.offlineId, progress: 20 }));
        __DEV__ && console.log('[INFO] Upload started');
        Upload.addListener('progress', uploadId, data => {
          __DEV__ && console.log(`[INFO] Progress: ${data.progress}%`);
          const e = data.progress / 100;
          dispatch(
            setUploadingProgress({ cancelId: uploadId, inspectionId: inspection.offlineId, progress: Math.ceil(20 + e * 80) })
          );
        });
        Upload.addListener('error', uploadId, data => {
          __DEV__ && console.log(`[ERROR] Upload error: ${data.error}%`);
          dispatch(setUploadingFinished({ inspectionId: inspection.offlineId }));
          reject(new Error('Inspection upload error'));
        });
        Upload.addListener('cancelled', uploadId, data => {
          __DEV__ && console.log(`[INFO] Upload cancelled!`);
          dispatch(setUploadingFinished({ inspectionId: inspection.offlineId }));
          reject(new Error('Inspection upload canceled'));
        });
        Upload.addListener('completed', uploadId, data => {
          __DEV__ && console.log('[INFO] Upload completed!');
          resolve(true);
        });
      })
      .catch(err => {
        __DEV__ && console.log('[ERROR] Upload error!', err);
        Bugsnag.error('[ERROR] Upload error!', err);
        dispatch(setUploadingFinished({ inspectionId: inspection.offlineId }));
        reject(err);
      });
  });
```

**Comment by medelvann** [comment]
i have this problem too , randomly upload successful and not any error and complete listener called after this bug happened.so i cant resolve promise for finish process upload.

**Comment by cadesalaberry** [comment]
I am having the same issue. Meanwhile I came up with a really ugly hack as a workaround.

Seeing that the `progress` callback is called, I just wait for it to return a value of 100%:

```js
handleUploadProgress = ({ progress }: Object) => {
  // HACK: 'completed' event is not always triggered on android
  if (Platform.OS === 'android' && progress === 100) {
    setTimeout(() => {
      this.handleUploadCompleted({ hack: true });
    }, 5000);
  }
};
```

This solution is a bit wonky as I don't even know if the `progress` callback always eventually return a `100` payload, and 5s is a random delay, but in my experience this hack has always worked for now.

The issue might be related to a performance problem. Initially around 90% of my calls would fail. After commenting 80% of my app (keeping only the page on which the upload happens), the "completed" event has always been triggered (so far).

I won't have time to debug it now, but here is my insight in case it helps someone.

**Comment by pedrosimao** [comment]
@cadesalaberry Good that the hack works for you. For me, the proposed solution would not work, since the `progress` callback also fails on Android sometimes.

**Comment by JesseDunlap** [comment]
My team and I are seeing a similar issue. Somewhat randomly none of the events (completed, progress, etc.) are triggered. So far this only seems to be affecting Android 9. 

We've tracked the issue down to `UploaderModule.java:149` (in the case of `progress` events). It would appear the `sendEvent` method gets called, but that event doesn't get fired in JavaScript.

Oddly enough, this issue generally goes away if we're debugging either the native code or our JavaScript code through the RN debugger. The events also have triggered correctly at least once or twice without debugging. Could this be some kind of race condition?

**Comment by JesseDunlap** [comment]
> My team and I are seeing a similar issue. Somewhat randomly none of the events (completed, progress, etc.) are triggered. So far this only seems to be affecting Android 9.
> 
> We've tracked the issue down to `UploaderModule.java:149` (in the case of `progress` events). It would appear the `sendEvent` method gets called, but that event doesn't get fired in JavaScript.
> 
> Oddly enough, this issue generally goes away if we're debugging either the native code or our JavaScript code through the RN debugger. The events also have triggered correctly at least once or twice without debugging. Could this be some kind of race condition?

Eventually we discovered that this was because the `UploadStatusDelegate` was being garbage collected. We were able to prevent this from happening by converting `statusDelegate` (`UploaderModule.java:145`) to an instance variable rather than an inline one. 

I have these changes in [a fork](https://github.com/zipline/react-native-background-upload), but I don't think it's a good or correct solution to the issue.

**Comment by hardcodet** [comment]
This might actually indicate a bug in the Android UploadService, since that delegate is actually fed into the library. @gotev, are you aware of the issue by any chance?

That being said, I stumbled over https://github.com/gotev/android-upload-service/wiki/Monitoring-upload-status which propagates another model that would survive non-foregrounded apps. Maybe the approach is problematic in the first place?

**Comment by gotev** [comment]
Delegates are good only when you never abandon the current activity, and it's suitable only for little uploads. If you receive a call or something else interrupts your app, the context is lost and so the delegate cannot be called. I always encourage to use the broadcast receiver approach, more specifically the version in which you declare a global broadcast receiver. That's the most reliable for long uploads and survives app switching and interruptions.

**Comment by dmarkowski** [comment]
Same problem on Android here. None of the listeners (progress, error, canceled completed) are called. It happens very often.

**Comment by StevePotter** [comment]
This is tough.  I updated the android background upload service to the latest version.  When I tried to use it, I got a bunch of errors.  Turns out that upgrading to the newest service requires that the app use AndroidX libraries.  Apparently React Native is behind the ball on AndroidX.  

As far as I know, the upgrade is not possible until React Native adopts AndroidX.  If someone else can volunteer some time, please try and get this PR working in your app: https://github.com/Vydia/react-native-background-upload/pull/125

https://github.com/facebook/react-native/issues/23112

**Comment by sanderpick** [comment]
I came across this while working on another library that includes @gotev's excellent upload library. FYI, I was only ever able to receive broadcast events within our library after forking and removing this one line that sets the broadcast's intent package, even though the action is correct: https://github.com/textileio/android-upload-service/commit/bca1d1af94b351be2d79bf9caa9b95c9a83c5d3c#diff-1fbd837a670d236e4986465b5871851aL33

Here's the PR that integrated the uploader library: https://github.com/textileio/android-textile/pull/39

**Comment by gotev** [comment]
@sanderpick seen your modification. It's strange that to make it work you have to remove that line. It's the way the Android system knows it's your app sending those events. Does RN mess with package namespace in some way, which makes that patch necessary? In that way you end up forking my library and lose the advantage of automatic updates when I release a new version.

**Comment by sanderpick** [comment]
@gotev my only thought is that the package comparison happens with the top-level package. Our library's package is `io.textile.textile`, but the demo app that uses our library in the same repo is `io.textile.textileexample`. Similarity, users of our lib would have a difference package.

Do you know of any other libraries that wrap your library? My hunch is that this was never noticed in this (https://github.com/Vydia/react-native-background-upload) library because it isn't correctly listening for events from a receiver.

**Comment by gotev** [comment]
@sanderpick the right thing in case of a wrap is to allow your library users to specify the package name and inject it into my library. All the other approaches are workarounds which can lead to unexpected behavior and errors

**Comment by jsancho** [comment]
We've been using the component in our app and noticed that the events were indeed not triggered.
We are running RN 0.60.4 which comes with AndroidX support out of the box.

> I have these changes in [a fork](https://github.com/zipline/react-native-background-upload), but I don't think it's a good or correct solution to the issue.
We've applied the changes on this fork and that seems to do the job for now, but can't help the feeling that this is not an ideal way to move forward.

@gotev Could you shed some light on what your plans are regarding this issue?
Do you have the time to look into this issue?
Do you have any external blockers? 
Can we help you somehow with testing/development of a patch?

Thanks so much, really appreciate the good work that you've put on this component.

**Comment by gotev** [comment]
As pointed out in https://github.com/Vydia/react-native-background-upload/issues/162 the source of all those problems is the delegates being used in the wrapping RN code. Actually it's not a problem of the upload library itself, but how it's wrapped.

**Comment by jsancho** [comment]
Oh I think finally get it. 

Please correct me if I'm wrong, my understanding is that react-native-background-upload has a dependency on your [Android upload service](https://github.com/gotev/android-upload-service) library.

So rather than expecting a fix for the current version of this component, this will be much easier to solve once the internal library has been upgraded [as per your plan](https://github.com/gotev/android-upload-service/issues/450)

that seems very reasonable to me, thanks for such an amazing effort!

**Comment by gotev** [comment]
Yes.

* Currently react-native-background-upload uses the delegates, which are the least recommended way and have many limitations, so to use broadcast receivers a rework is necessary
* Upload Service 4 will be out soon with many improvements. Delegates are going to be dropped. and react-native-background-upload will need some rework.

So the better IMHO is to wait a little bit and land directly on 4.0 version

**Comment by gotev** [comment]
Upload Service 4.0.0 Alpha 01, 100% Kotlin with Android 10 support is here for developer preview! [Check this issue for more information](https://github.com/gotev/android-upload-service/issues/462)

**Comment by anagovitsyn** [comment]
So, how can I disable updating UploaderModule.java with each app build? I replaced it with a fixed version, but upon each app build original buggy UploaderModule.java replaces fixed version.

**Comment by gotev** [comment]
Upload Service 4.0.0 completed its first Alpha 01 stage. Alpha 02 here with ready to test delegates replacement. [Check this issue for more information](https://github.com/gotev/android-upload-service/issues/463)

**Comment by anagovitsyn** [comment]
> So, how can I disable updating UploaderModule.java with each app build? I replaced it with a fixed version, but upon each app build original buggy UploaderModule.java replaces fixed version. I use [this](https://github.com/Vydia/react-native-background-upload/issues/129#issuecomment-470747496) fix and it works ok.

package replaced with original files only when adding new packages through yarn add or npm install, so I was wrong saying that it was replaced each time with app build.

**Comment by osrl** [comment]
In the master branch of this library broadcast receivers are implemented. But I think UploadReceiver should be registered in a Service, and this service should be started foreground. Am I wrong?

**Comment by NicholasIoanJones** [comment]
I'm pretty new to Android but I'm not sure this is an architectural problem. My upload works sometimes - not often - and fails the rest. This seems to be common from the above.
Generally I see maybe a single progress event and then nothing else in the console (from event handlers in my own code). 
I've just put logging into the UploaderModule though and there are more adb events being logged in the statusDelegate.onProgress AND the sendEvent method than hit the event handler in my code. So this is not an Android -> RN issue but RN -> client component.
How can the RCTDeviceEventEmitter work sometimes and not others?

**Comment by osrl** [comment]
I'm pretty new to React Native and pretty old to Android :) I'm almost sure that UploadReceiver should be registered in a foreground Service. And the Service should be stopped on an appropriate time, maybe after complete event

**Comment by NicholasIoanJones** [comment]
> I'm pretty new to React Native and pretty old to Android :) I'm almost sure that UploadReceiver should be registered in a foreground Service. And the Service should be stopped on an appropriate time, maybe after complete event

You may very well be correct, but that doesn't explain to me why I'm seeing events in the UploaderModule which are not hitting the event handlers in my code. Feels like there are a few things going wrong yet this used to work before I upgraded RN -> 0.61 and this library from 4.4 to 5

**Comment by NicholasIoanJones** [comment]
> > My team and I are seeing a similar issue. Somewhat randomly none of the events (completed, progress, etc.) are triggered. So far this only seems to be affecting Android 9.
> > We've tracked the issue down to `UploaderModule.java:149` (in the case of `progress` events). It would appear the `sendEvent` method gets called, but that event doesn't get fired in JavaScript.
> > Oddly enough, this issue generally goes away if we're debugging either the native code or our JavaScript code through the RN debugger. The events also have triggered correctly at least once or twice without debugging. Could this be some kind of race condition?
> 
> Eventually we discovered that this was because the `UploadStatusDelegate` was being garbage collected. We were able to prevent this from happening by converting `statusDelegate` (`UploaderModule.java:145`) to an instance variable rather than an inline one.
> 
> I have these changes in [a fork](https://github.com/zipline/react-native-background-upload), but I don't think it's a good or correct solution to the issue.

It seems some event messages dispatched from the Android background service were not getting through to the RN module. Logging in the Android RN code confirmed the issue was between the native service and the RN-B-U and not between RN-B-U and our code.
Jesse's comment provided the solution for us. 
This seems a rational solution to the problem and I'm a little surprised this hasn't made it into the code base yet.

**Comment by osrl** [comment]
Because it probably causes a memory leak (I didn't test). Also, master branch of this library abandoned UploadStatusDelegate and uses BroadcastReceivers, which is the right way to do this. But It's not released yet I think. Also, as I've said before It registers the BroadcastReceiver in the wrong place. I made some changes and register this BroadcastReceiver from a foreground service and It works great. Even if the application is killed by the user, events are received. This foreground service I've added creates another notification and It looks ugly though. I'm going to make a pull request anyway.

**Comment by gotev** [comment]
@osrl Upload Service is now on Beta 1 and I strongly recommend you start migrating from the old one, because many issues are now solved, using also Lifecycle aware components. It's the right moment to provide me feedback before I finalize it and to eventually fix some things which may pop up

**Comment by osrl** [comment]
>If the app gets killed, on stock Androids the root app context dies and this causes foreground service to die, too.
Is this new on android 9 or 10? By killing I mean "killing by swiping". My foreground service doesn't die when it's killed by swiping. 

I've made a pull request by the way. I'm sorry but 4.0 min SDK is 21 and we are not ready to move forward yet :) I hope maintainers of this repo will migrate it. I would be glad to help if they decide to migrate.

**Comment by gotev** [comment]
If it's killing by swiping then with startForeground (which is done also in upload service), the app context does not get killed, only its activities. If you kill the app from the settings > apps or by tapping app info, then there's nothing you can do unless you have deferred the job to WorkManager.

Regarding minSDK 21, it depends solely on your user base and the type of service you're providing (if it's critical and you have many users with API < 21). 

API 21 is mainly a security move, which I've done following Square OkHttp 4. More details on upload service issue 450.

**Comment by osrl** [comment]
I totally understand your move. I've checked your 4.0 job, great job by the way. But this and WorkManager is another times job for us. I'm aware of killing from settings thing. That's something we can afford I think. 
Also, my fix creates another notification for this service and it looks really ugly. Is there any way to register my `UploadServiceBroadcastReceiver` from `UploadService`?

**Comment by gotev** [comment]
@osrl no there's not, but you can register that receiver at app level to use app context, which is kept alive while the service is in foreground

**Comment by osrl** [comment]
@gotev I register it in a new foreground service which creates a new notification. It's killed otherwise.

**Comment by philsam** [comment]
Apply the above workaround using a temporary patch like this
create a patch folder in your main directory and a file `fix.sh`
`cp ./patch/UploaderModule.java ./node_modules/react-native/Libraries/Image/ImageStylePropTypes.js ./node_modules/react-native-background-upload/android/src/main/java/com/vydia/UploaderModule.java`

add the command to your post-install in package.json 
  `"postinstall": "npx jetify && sh ./fix.sh"`

**Comment by JB-CHAUVIN** [comment]
Hello, same issue goes for me....
