### ISSUE TITLE
IOS: Upload with file:// error

### ISSUE THREAD

**Issue by phuongluu98** [Vydia/react-native-background-upload#13]
Hi there,

I have params on header like this:

var path = "/var/mobile/Containers/Data/Application/Documents/Video.mp4";
var options = {
            url           : "http://upload.........",
            path        :  'file://'+path,
            method   : 'POST',
            headers  : {
                    'Accept'    : 'application/json'
                },
            files : [{
                    name        : 'coverFile',
                    filename    : name,
                    filepath    : path,
                    filetype    : 'video/mp4',
                }],
            }

But I cannot upload correct because the final path is : 'file:///var/mobile/Containers/Data/Application/Documents/Video.mp4’

Any help please ?

**Comment by StevePotter** [comment]
Do you get any messages?
