### ISSUE TITLE
support non rest endpoints

### ISSUE THREAD

**Issue by shakibbzillow** [Vydia/react-native-background-upload#136]
Hi,

We are using apollo graphql and are uploading this to it, but apollo graphql doesn't sene 200 when there is an error, it returns a 200 w/ a response that contains the error.

Is there any plans on supporting non-rest endpoints?

**Comment by TSMMark** [comment]
Hi there are no plans right now but graphql is just http with a specific payload so it shouldn't be too hard to implement I imagine if you wanted to take a stab at it.
