### ISSUE TITLE
Upload fail on android

### ISSUE THREAD

**Issue by peacepostman** [Vydia/react-native-background-upload#137]
### Description

Hello, we are having issues regarding upload on android. We use the library **react-native-image-crop-picker** to select files.

Everything is working fine on ios but android doesn't want to upload the media. We were previously using **react-native-image-picker** and we faced a similar issue with "Unsupported Scheme", which was resolved by calling path instead or uri, on the uploaded file.

Did any of you faced the same issue here ? We applied this trick (Vydia/react-native-background-upload#115) but the upload is still failing. The error is triggered in an android notification saying "File upload : Error during upload"

Any help appreciated.

Best regards,

### Additional Information

React Native version: 0.59.3
react-native-background-upload: 5.0.0
react-native-image-crop-picker 0.23.1
Platform: Android
Development Operating System: MacOS

**Comment by peacepostman** [comment]
The problem was caused by a certificate error on our server. Nevertheless i am now facing the issue with the listener not triggered 😞

**Comment by AugustoAleGon** [comment]
@peacepostman How did you handle the problem? Because in Android I try to upload or find the information of the file with `Upload.getFileInfo(path)` and returns false. I wanna know what did you do?
