### ISSUE TITLE
[iOS] upload photo fail

### ISSUE THREAD

**Issue by OPY-bbt** [Vydia/react-native-background-upload#141]
I want to upload photo which come from CameraRoll.getPhotos. However, uri don't support ph:// schema?

**Comment by TSMMark** [comment]
Correct

**Comment by assaqqaf** [comment]
Any idea how to upload `ph://` uri through the package?

**Comment by TSMMark** [comment]
Is there a way to convert the `ph://` protocol to `file://` ?
