### ISSUE TITLE
Share Extension Support

### ISSUE THREAD

**Issue by narehart** [Vydia/react-native-background-upload#146]
When trying to use this package in a share extension I'm encountering this error:
```
{ 
  id: '0',
  responseBody: null,
  error: 'The operation couldn’t be completed. (NSURLErrorDomain error -995.)'
}
```
I don't know enough about Objective-C to really diagnose this issue but I think it might have something to do with the utility method used to copy the PHAsset to the temp directory. Let me know if you need anymore info.

**Comment by Palid** [comment]
@narehart did you correctly add all the required informations for share extension too? You need to setup groupID and it needs to be passed down the tree to the `react-native-background-upload`, which it doesn't support it so far. I'll be doing a pull request for that.
