### ISSUE TITLE
Is this repository still active?

### ISSUE THREAD

**Issue by APZelos** [Vydia/react-native-background-upload#156]
First of all, I would like to thanks everyone involved in this repository but seems like not much going one in the last months. When we tried to update the react-native version in our project we faced some issues with the latest version of react-native-background-upload. 

To resolve these issues I forked this repo and I've started merging pull requests and fixing some issues. 

Should I continue working on my fork or open some pull requests here?

[fork](https://github.com/APZelos/react-native-background-upload)

**Comment by karanpratapsingh** [comment]
Thank you for your contributions, I think you should definitely continue working on your fork and contact this repo's author to make you a collaborator or add a note in this repo's readme to refer to your fork for newer versions

**Comment by TSMMark** [comment]
PRs more than welcome, I would happily add you to as a contributor @APZelos

**Comment by karanpratapsingh** [comment]
@TSMMark Awesome, @APZelos please don't delete your forked repo, I am using it in a prod app now 😅

**Comment by APZelos** [comment]
@TSMMark I am more than happy to create a pull request with the changes I made! I will look into it as soon as I can

@karanpratapsingh I will leave it for now as I am also using it in a production app but it would be better if we come back to using this repo as soon as the pull requests are merged
