### ISSUE TITLE
Immediate crash on android P and Q

### ISSUE THREAD

**Issue by karanpratapsingh** [Vydia/react-native-background-upload#159]
Calling the Upload.start(...) causes immediate crash on devices with android p and q

Any help would be appreciated

**Comment by karanpratapsingh** [comment]
just add the following permissions on android

```
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
```

**Comment by TSMMark** [comment]
Thanks for reporting. Is there a gap in our documentation? Please feel free to submit a PR to update any missing documentation, I will merge it.

**Comment by karanpratapsingh** [comment]
@TSMMark I'll send it soon, thanks. Btw awesome work on this package, tho you should consider looking at @APZelos fork, it has much better support

**Comment by TSMMark** [comment]
Hi @apzelos would you consider submitting a PR to merge your changes into the main repo? I could make you a project collaborator to assist in any further changes you'd like to see included
