### ISSUE TITLE
No Test Project

### ISSUE THREAD

**Issue by StevePotter** [Vydia/react-native-background-upload#16]
It would be great to see a test project for this package.  Right now everyone is testing on different backends and apps.

The app will simply let you choose and upload a file.

The backend can be a basic Express app that has a single route for uploading a file.  It can just save the file to /tmp.

Any ideas here before I implement it?

**Comment by eard7** [comment]
First of all thank you so much for your hard work. I would appreciate if you could explain how to get the file in the backend? I mean, i have a nodejs express server, but i can't see the file uploaded. I should get it as a file or as a body param? What param key should i use to access the uploaded file? Thanks in advance!

**Comment by StevePotter** [comment]
Hi @eard7 we use a Ruby app but it's probably part of req.files.  You might need some middleware.  It's been a long time since I did a request app, which is selfishly part of the reason I wanted to make the example app.

**Comment by metallurgical** [comment]
@eard7 you did know now what params? i too facing this issues
