### ISSUE TITLE
assets-library support

### ISSUE THREAD

**Issue by jjhesk** [Vydia/react-native-background-upload#17]
Im new to object-c and RN. I really wish that `assets-library://` can be supported in the upcoming version. I did some research and it came up with [some discussions](http://stackoverflow.com/questions/31548925/how-to-access-image-from-native-uri-assets-library-in-cordova-for-ios) and [here](http://stackoverflow.com/questions/3837115/display-image-from-url-retrieved-from-alasset-in-iphone) about how to do that in cordova but havent get anything from RN. While `ALAssetsLibrary` is deprecated in xcode 8 and above. Check out this [repo](https://github.com/aroth/react-native-uploader) for the full support.

**Comment by StevePotter** [comment]
Hi @jjhesk thanks for writing.  We have already discussed this and we are open to it.  It's just a tricky implementation, as you can see from https://github.com/aroth/react-native-uploader.  I plan on doing it one day but would be delighted if someone else did it sooner.

**Comment by StevePotter** [comment]
@jjhesk the library supports `assets-library://` now, thanks

**Comment by Wilson-Lim** [comment]
data uploaded with "assets-library://" always ended up as binary format ?

or any idea how I can upload to server as jpg formatted file ?
