### ISSUE TITLE
Uploading images and JSON

### ISSUE THREAD

**Issue by rdgomt** [Vydia/react-native-background-upload#177]
Hey guys,

It is not an issue, so sorry if it is not the right place, but I am kind of lost.

I need to upload a group of images (like 3-4) which are related to each other. Then, if successful, make a POST to another route with normal JSON body. Question is: can I do this with this library?

**Comment by augustosamame** [comment]
Sure you can. This library does not support multiple uploads but you can initiate 4 uploads, which will each resolve to a promise. Once all promises 4 have resolved with no error you can send the POST wherever you wish.
