### ISSUE TITLE
How about a new version?

### ISSUE THREAD

**Issue by xeroxoid** [Vydia/react-native-background-upload#181]
It seems that multiple pull requests have been merged but no new version has been released since April. Any ideas?

**Comment by pribeh** [comment]
Sorry for the bump.

**Comment by AwanesowArtem** [comment]
Guys any ETA?:)

**Comment by piotrponikowski** [comment]
Any news?

**Comment by reime005** [comment]
@piotrponikowski you may checkout react-native-background-upload@5.3.0-beta.0

**Comment by AwanesowArtem** [comment]
> @piotrponikowski you may checkout react-native-background-upload@5.3.0-beta.0

Thanks for letting us know. Can we find change log for this version somewhere?
