### ISSUE TITLE
How can I upload multiple file using this

### ISSUE THREAD

**Issue by AliRehman7141** [Vydia/react-native-background-upload#194]

**Comment by AliRehman7141** [comment]
I need to upload an image and a pdf file in single API how can I do this using this library

**Comment by lucasluca** [comment]
i have the same question

**Comment by petrbela** [comment]
I'm not sure the HTTP protocol even supports uploading multiple files using a single request. However, you should be able to run two separate background uploads.

**Comment by AliRehman7141** [comment]
Thanks
