### ISSUE TITLE
Android: Support content:// URI

### ISSUE THREAD

**Issue by xubmuajkub** [Vydia/react-native-background-upload#195]
I've used the `React Native Document Picker` for picking files to upload to server. It works fine on iOS which the file URI is `file://`, but when it comes to Android which using `content://` URI, there's error thrown `Parameters must be string key/values` (I used `multipart` type).
I was tried using `React-Native-Fetch-Blob` to get the real path of the file, but when I try on upload the file it said `Unsupported scheme file://path.to.file`.
I hope that this library will support `content://` soon.

**Comment by sobanarshad85** [comment]
any solution you found?

**Comment by xubmuajkub** [comment]
> any solution you found?

If I remember correctly, it's the FormData I used itself is the problem. The way React-Native and JavaScript handle are different. So make sure you have correct FormData or Blob object

**Comment by sobanarshad85** [comment]
path:
        Platform.OS === 'ios' ? image.uri : image.uri?.replace('file://', ''),


it worked for me
