### ISSUE TITLE
Android Application force close when add/link component

### ISSUE THREAD

**Issue by RZulfikri** [Vydia/react-native-background-upload#2]
I got error after link/add this component to my project, my app always force close when it active. i have no idea with the error, because no error log found. i attach a screenshoot.

my step :
- npm install https://github.com/Vydia/react-native-background-upload.git 
- react-native link react-native-background-upload

and i'm not even use the component in my code.
then it try to create new project and it work fine, buat why if i use this in my old project i got that error. is there any dependecy in this componet, or maybe it have conflict with other component ?

[![Screenshot_1484194737.png](https://s29.postimg.org/in1jd22zr/Screenshot_1484194737.png)](https://postimg.org/image/yy1n9dfhf/)

thanks

**Comment by StevePotter** [comment]
@RZulfikri what version of RN are you using?  Can you try running the project from Android Studio?
