### ISSUE TITLE
If I want to upload a file just like html from, How can I config the from name ?

### ISSUE THREAD

**Issue by skyworld** [Vydia/react-native-background-upload#20]
If I want to upload a file just like html from, How can I config the from name ?

**Comment by nonotest** [comment]
If you have control over the backend you can do something like this:

const fileName = `${Date.now()}_${image.fileName}`
    const options = {
      url: UPLOAD_URL,
      path: image.uri,
      method: 'POST',
      // Below are options only supported on Android
      notification: {
        enabled: true
      },
      // FIXME..
      headers: {
       'X-File-Name': fileName
     },
    }

and use the X-File-Name header... didnt find anything better since I couldnt get responseBody to work on iOS

**Comment by StevePotter** [comment]
@nonotest responseBody works now on iOS.  Enjoy
