### ISSUE TITLE
1.0.0 fails to install on RN 0.42.3

### ISSUE THREAD

**Issue by thatjuan** [Vydia/react-native-background-upload#21]
As per #18, 1.0.0 should support RN 0.40+

However, when trying to install it I get 

`npm WARN react-native-background-upload@1.0.0 requires a peer of react-native@>=0.30.0 <0.39.0 but none was installed.`

The reason appears to be:

https://github.com/Vydia/react-native-background-upload/blob/master/package.json#L22

I just sent in a PR to correct this. https://github.com/Vydia/react-native-background-upload/pull/22

**Comment by StevePotter** [comment]
@thatjuan thanks.  Fixed and published in npm as v1.1.  Thanks!
