### ISSUE TITLE
Upload error while uploading to s3 bucket

### ISSUE THREAD

**Issue by HarshMB** [Vydia/react-native-background-upload#215]
When i will upload image, it will show progress 0% to 100% after that it will display "Error : Upload error"
I am uploading file like this:

         import Upload from 'react-native-background-upload'
         import { S3Policy } from '../../node_modules/react-native-aws3/src/S3Policy';

         const options = {
                  type: 'multipart',
                  method: 'POST’,
                 url: “S3 bucket URL”
                 field: 'file',
                 path: filePath,
                 parameters: {
                               ...S3Policy.generate({
                                bucket: ‘bucket name,
                                region: ‘bucket region’,
                                accessKey: ‘key’,
                                 secretKey: ‘secKey’,
                                successActionStatus: 201,
                                key: ‘fileName’,
                                date: new Date(),
                                contentType: file.type,
                              }),
                         },
             };

            const uploadId = await Upload.startUpload(options)
           
            Upload.addListener('progress', uploadId, (data) => {
                console.log(`Progress: ${data.progress}%`)
            })
            Upload.addListener('error', uploadId, (data) => {
                console.log(`Error: ${data.error}`)
            })
            Upload.addListener('cancelled', uploadId, (data) => {
                console.log(`Cancelled!`)
            })
            Upload.addListener('completed', uploadId, (data) => {
                              console.log('Completed!')
            })

Output:
Progress: 0%
Progress: 31%
Progress: 72%
Progress: 100%
Error: Upload error

**Comment by matamicen** [comment]
@HarshMB I also have an error to upload to s3 with pre signed function, could you share with me the code that works for you? Thanks!!

**Comment by matamicen** [comment]
@HarshMB we fixed that problem changing the pre signed function to allows more fileSize ... I don't if it is your case but it was ours.

**Comment by rahulnainwal** [comment]
@HarshMB how you solved this issue. @matamicen where is pre signed function, can you please explain it.

**Comment by matamicen** [comment]
@rahulnainwal check [this](https://github.com/Vydia/react-native-background-upload/issues/221)

Hope it helps :)

**Comment by rahulnainwal** [comment]
Thank you @matamicen, i am getting this issue because of wrong access key and secret key.

**Comment by iOrcohen** [comment]
@matamicen Thanks for the details explanation !
I actually did the same as you did, and I'm facing error of :
```"java.net.SocketException: Broken pipe"```
Did you know anything about it ?
thanks ahead!
