### ISSUE TITLE
responseBody on IOS

### ISSUE THREAD

**Issue by nonotest** [Vydia/react-native-background-upload#23]
Hello, 
I have tried a few workarounds to try and get a response body on IOS but to no avail.
My use case is the server is sending the URL back after the upload as a JSON string.

If anyone has any idea or knows what to do?

I tried to add a `didReceiveData:(NSData *)receivedData` delegate but no luck.

Cheers,

**Comment by chrisharrison** [comment]
I have the same use case.

**Comment by chrisharrison** [comment]
@nonotest I've managed to get the responseBody working on iOS.

PR is here:
https://github.com/Vydia/react-native-background-upload/pull/24

Please note that it does not support automatically decoding a JSON response. So you'll have to do that with something like `JSON.parse()` on the Javascript side.

**Comment by nonotest** [comment]
Wow well done thanks ! I'll have a look tomorrow.

**Comment by StevePotter** [comment]
Hey all, why do you need this?  I'm trying to understand the use case.

**Comment by chrisharrison** [comment]
1. The use case is uploading a large image to an image service where the
response is the ID of the newly stored image.

2. Android supports responseBody so why would you want to continue with a
discrenpency between iOS and Android?

**Comment by nonotest** [comment]
Yep above post sums it up.

If you need to re-use the URL of the uploaded image anywhere else in the app you will need to get it from the response body.

For example you have a chat, you upload an image to a cloud storage, you need to be able to post the URL back to all the connected clients or whatever.

**Comment by StevePotter** [comment]
Thanks guys.  I'll get the PR in today and publish to npm.
