### ISSUE TITLE
Android Application Error Response Code 413

### ISSUE THREAD

**Issue by RZulfikri** [Vydia/react-native-background-upload#3]
Hi, its me again..
I'm trying your component, and i got this error log 

[![Screen Shot 2017-01-13 at 12.57.53 AM.png](https://s28.postimg.org/5tlcvd4yl/Screen_Shot_2017_01_13_at_12_57_53_AM.png)](https://postimg.org/image/xgy29gq55/)

it say, error response code 413. I think thats error from my server. But when i use post man and other react upload method (i try step from this link https://github.com/g6ling/React-Native-Tips/tree/master/How_to_upload_photo%2Cfile_in%20react-native) no error found.

am i miss something ?

btw my code look like this.

    const options = {
        url: 'http://test.exsample.com/api/file_upload.php',
        path: this.state.file_path,
        headers: {
          'my-custom-header': "s3headervalueorwhateveryouneed"
        }
      }
      console.log(options.path)
      Upload.startUpload(options).then((uploadId) => {
        console.log('Upload started')
        Upload.addListener('progress',uploadId, (data) => {
          console.log(`Progress: ${data.progress}%`)
        })
        Upload.addListener('error',uploadId, (data) => {
          console.log(`Error: ${data.error}`)
        })
        Upload.addListener('completed',uploadId, (data) => {
          console.log("response Code : "+data.responseCode)
          console.log("response Body : "+data.responseBody)
          console.log(`Completed!`)
        })
      }).catch(function(err) {
        console.log('Upload error!',err)
      });

thanks again

**Comment by StevePotter** [comment]
The code looks fine.  Can you see exactly what headers are being included when you use an alternative upload method?  Have you tried iOS?
