### ISSUE TITLE
Expo instructions don't explain how to link

### ISSUE THREAD

**Issue by Fmstrat** [Vydia/react-native-background-upload#311]
Hi, I've read the expo instructions that were part of https://github.com/Vydia/react-native-background-upload/pull/76, however they basically just say to eject the project and link as per the other instructions.

However, in an expo project where you're using EAS to build, you don't have an `ios` or `android` folder, so the instructions for linking don't make sense. It also doesn't explain if you're still able to use expo, etc. I'm not sure where to go from here.

Thanks!

**Comment by Fmstrat** [comment]
Nevermind. Realize this happens as part of ejecting.

**Comment by alamothe** [comment]
Can it work with EAS build without ejecting?

**Comment by usmansbk** [comment]
> Can it work with EAS build without ejecting?

@alamothe did you test with EAS?

**Comment by talvbansal** [comment]
@usmansbk / @alamothe  did you get this with a custom dev client or did you need to eject?
