### ISSUE TITLE
Issue with iOS image upload

### ISSUE THREAD

**Issue by midhunevolvier** [Vydia/react-native-background-upload#322]
Hi, I tried to upload an image from my camera and gallery on iOS. The image upload was completed, but the upload response URL was invalid. I am not able to see the uploaded image.
After downgrading the package version, **Version 6.2.2** is working and other versions above it are not.

Can anyone help us?

Thank you!

**react-native v0.70.6**
**react-native-background-upload: v^6.6.0**

**Comment by midhunevolvier** [comment]
Can anyone help us?

**Comment by yaroslavkuzn** [comment]
I'm also getting this problem when updated to react-native v0.70.6! 
Any update? 
If need more details from my side pls ping me

**Comment by midhunevolvier** [comment]
I am closing the issue. My issue is with the image path, I need to append 'file://' with path in iOS.

**Comment by nero2009** [comment]
Hi @midhunevolvier I want to know if you have this library working for uploads on android? Cs I recently upgraded t the latest react native version 0..70+ and this  library stops working on android

**Comment by Danushka50** [comment]
> I am closing the issue. My issue is with the image path, I need to append 'file://' with path in iOS.

Thanks @midhunevolvier. The solution works fine on iOS.
