### ISSUE TITLE
Unable to build on Android with RN 0.45.1:  AAPT: Error retrieving parent for item:

### ISSUE THREAD

**Issue by itinance** [Vydia/react-native-background-upload#37]
On android with react native 0.45.1 this library can't be build and throws the following errors:

```
./android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

./android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

./android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

./android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
```

Steps to reproduce:

```
react-native init test --version react-native@0.45.1
cd test
yarn add react-native-background-upload
react-native link
cd android && ./gradlew assembleDebug
```

With react-native 0.42 this is not an issue.

Some hints about it: i am not that familiar with android native but from some people i've heard that it can have do something with buildToolsVersion.

**Comment by itinance** [comment]
Upgrading the buildToolVersion in my example application will solve this issue, but continues then with:

>Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lokhttp3/internal/ws/WebSocketReader$FrameCallback;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lokhttp3/internal/ws/WebSocketReader$FrameCallback;

Maybe we should add some hints to the README about those things?

**Comment by devLaaziz** [comment]
:( me too

**Comment by chilic** [comment]
> Ensure Android SDK versions. Open your app's android/app/build.gradle file. Ensure compileSdkVersion and targetSdkVersion are 25. Otherwise you'll get compilation errors.

It's from readme.

**Comment by pablote** [comment]
The readme mentions this in the `Manual Native Library Linking` section, which you probably skip if you do automatic linking.

**Comment by laurindo** [comment]
I´ve resolved change my build.gradle inside android/build.gradle changing:
old:
android: {
compileSdkVersion 23
buildToolsVersion "23.0.1"
...
}

dependencies: {
compile "com.android.support:appcompat-v7:23.0.1"
...
}

to
android: {
compileSdkVersion 24
buildToolsVersion "24.0.1"
...
}

dependencies: {
compile "com.android.support:appcompat-v7:24.0.1"
...
}
