### ISSUE TITLE
method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by binitpatel** [Vydia/react-native-background-upload#40]
node_modules\react-native-background-upload\android\src\main\java\com\vydia\UploaderReactPackage.java:23: error: method does not override or implement a method from a supertype
  @Override
  ^
3 errors
Incremental compilation of 1 classes completed in 0.556 secs.
:react-native-background-upload:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

**Comment by StevePotter** [comment]
Thanks, I think this is a bug with the latest React Native.  What version of RN do you have?

**Comment by ovr** [comment]
It's a break change inside `RN 0.47`

refs https://github.com/Vydia/react-native-background-upload/pull/39

Thank

**Comment by StevePotter** [comment]
Fixed in 4.0.0.  Thanks everyone!
