### ISSUE TITLE
Base64 support ?

### ISSUE THREAD

**Issue by hamxabaig** [Vydia/react-native-background-upload#47]
Hey, Thanks for this great library, works perfectly. I just wanted to ask if this will work with base64 string ?

Thanks

**Comment by StevePotter** [comment]
Hi @hamxabaig no, this currently doesn't.  What's your use case?  Closing this issue but I'd like to keep discussing it.

**Comment by hamxabaig** [comment]
@StevePotter I didn't want to save the image first and then upload it. I had access to stream only. So I thought it'd be efficient if I can just use the stream and don't save it in some tmp folder. Thats why

But I don't think so its possible because this package uses `android-upload-service` internally and they don't support it too.

I'm not sure if its even possible but I went with the approach where I save it first in some tmp folder and then upload it.
