### ISSUE TITLE
 Handling iOS Background Activity

### ISSUE THREAD

**Issue by kaelumania** [Vydia/react-native-background-upload#49]
When I do understand the [docs](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/URLLoadingSystem/Articles/UsingNSURLSession.html) correctly (section **Handling iOS Background Activity**), we should add the proposed handling, to get the right callbacks for upload completion. I am not 100% sure what the implications are and what is required.

Some more resources:
https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622941-application
https://developer.apple.com/documentation/foundation/nsurlsessiondelegate/1617185-urlsessiondidfinisheventsforback

**Comment by TSMMark** [comment]
Hey @kaelumania a PR would be welcome :-)

**Comment by kaelumania** [comment]
Yeah, bur as already mentioned. I am not sure what to do. If its really required. Fir example, the nsurlsession ist not released, thus recreation might not be necessary. Further the design would change, as it might require 1 session per upload task. I guess. But adain, I am not completely sure.

**Comment by StevePotter** [comment]
@kaelumania thanks for writing.  Can you help me understand what the problem is with the package currently?  The iOS module already implements `URLSession:task:didCompleteWithError:`, which notifies you when an upload task has finished (with or without error).  As far as I know it's correct already.

**Comment by sraka1** [comment]
@StevePotter why was this closed?

As posted above, users should be instructed to implement `application:handleEventsForBackgroundURLSession:
completionHandler:` in their AppDelegate and in turn call a method on VydiaRNFileUploader...

**Comment by StevePotter** [comment]
@sraka1 thanks for writing.  I checked and we were calling the appropriate files.  I also can't do much with this bug report.  A screenshot or anything would be nice.  I can't fix what I can't reproduce.  I would not want to ask people to add AppDelegate code unless they absolutely had to.  If you can get me more information, and maybe a quick PR to fix it, we can continue.  How does that sound?

**Comment by TSMMark** [comment]
If you could implement a minimal repro by forking our example app https://github.com/Vydia/ReactNativeBackgroundUploadExample that would be ideal
