### ISSUE TITLE
Module VydiaRNFileUploader requires main queue setup ...

### ISSUE THREAD

**Issue by kaelumania** [Vydia/react-native-background-upload#52]
`Module VydiaRNFileUploader requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.`

**Comment by AlfredOdling** [comment]
same

**Comment by StevePotter** [comment]
Hey, thanks.  For now you can ignore that message.  I'll add a fix to the package.

**Comment by StevePotter** [comment]
Done in https://github.com/Vydia/react-native-background-upload/pull/61
Published just now to npm version 4.2.0
