### ISSUE TITLE
Video uploads larger than ~100MB fail on iOS

### ISSUE THREAD

**Issue by adam-denny** [Vydia/react-native-background-upload#53]
I keep running into this issue on iOS when uploading a video. Videos of any size longer than about 100mb consistently fail, with the message "Lost connection to background transfer service". Under that size they seem to work fine, but larger files fail before getting to the progress phase.

**Comment by TSMMark** [comment]
Hi, please make sure your server is configured to support file uploads larger than the size you mentioned

**Comment by adam-denny** [comment]
It is, uploads > 2GB are supported on the web platform and succeed just fine. Non-background uploads > 100MB succeed using other packages (such as react-native-fetch-blob) also succeed but don't work in the background. This is definitely not a server-side issue.

**Comment by TSMMark** [comment]
possibly related to #54?

**Comment by mlasy** [comment]
not a solution, but maybe a workaround: i had the same issue, what i did was to reduce the videoquality. 100mb of recorded video are very large and consumes the mobile data of the user in no time.
(you're using react-native-camera? -> captureQuality: Camera.constants.CaptureQuality.low).

**Comment by cristianoccazinsp** [comment]
Trying to debug this as well, but large files don't seem to be uploading successfully.

**Comment by jkerb8** [comment]
Did you guys ever determine how to fix this issue? I'm running into the same problem with video uploads. Unfortunately, dropping the quality below 720p isn't an option for me. I can also confirm that it is not a server-side problem.

**Comment by cristianoccazinsp** [comment]
I wasn't able to fix it.  The only way around it seems to not use a multipart upload, but rather a plain file upload. This way the file is read directly from the file system on the native side and it doesn't need to be loaded into memory.
