### ISSUE TITLE
Chunked uploads

### ISSUE THREAD

**Issue by psyon** [Vydia/react-native-background-upload#54]
Are there any plans to implement chunked uploads?  My site runs through Cloudflare, so uploads are restricted to 100MB in size.  I've worked around this with the website uploads by using chunked uploads, so that only a few megabytes are sent in each chunk.  It also allows the file to be resumed.

**Comment by TSMMark** [comment]
no plans but PRs welcome ;)

**Comment by psyon** [comment]
I am new to react-native, so not sure if I can do the changes needed, but ill give it a shot.
