### ISSUE TITLE
Upload error! Error: NSInvalidArgumentException

### ISSUE THREAD

**Issue by AlfredOdling** [Vydia/react-native-background-upload#56]
Hi! I am trying to convert from an iOS camera roll asset to the file asset format of "file://.." 

An image uri would be:
"assets-library://asset/asset.JPG?id=A19B54F5-367B-4992-B647-AF7705338124&ext=JPG"

I then use RNFetchBlob.wrap() and gets: 
"RNFetchBlob-file://assets-library://asset/asset.JPG?id=BF29BC40-EBAB-43FD-A451-B2AC21842DD8&ext=JPG"

That didn't work so I sliced out the "RNFetchBlob-" part to make it "file://..." and that didn't work either. I get the error: 
"Upload error! Error: NSInvalidArgumentException"

How do I convert in the right way?

**Comment by radreamer** [comment]
Same issue

**Comment by abhirajevolvier** [comment]
@AlfredOdling did you found any solution for that. Thanks.

**Comment by StevePotter** [comment]
@AlfredOdling thanks for reporting this.  I've never attempted what you're describing.  I would be happy to get it working.  All I ask from you is a sample project to work off.  

Can you provide a sample app for me to use?  The best thing would be to fork https://github.com/Vydia/ReactNativeBackgroundUploadExample and integrate RNFetchBlob into it.  Then I can make the fix quickly.  Thanks!

**Comment by StevePotter** [comment]
@AlfredOdling would it be easiest if react-native-background-upload just supported `asset-library://' directly?  If so, perhaps we should just focus on that.

**Comment by abhirajevolvier** [comment]
Here is my code snippet which shows the same error.

Code: 

  imageUpload = (image) =>{
    console.log(image.path)
    // /Users/EvolvierTechnologies/Library/Developer/CoreSimulator/Devices/88508649-4AAF-4096-80D8-94D4CDC7D5C1/data/Containers/Data/Application/23F21D39-9462-47D3-95AE-B488A5ACA8C7/tmp/react-native-image-crop-picker/0DC833CD-53B0-46BA-9020-78BF70E4CA95.jpg

    const options = {
      url: 'http://localhost:3000/api/upload',
      path: image.path,
      method: 'post',
      type: 'raw',
      // Below are options only supported on Android
      notification: {
        enabled: true
      }
    }

    Upload.startUpload(options).then((uploadId) => {
      console.log('Upload started')
      Upload.addListener('progress', uploadId, (data) => {
        console.log(`Progress: ${data.progress}%`)
      })
      Upload.addListener('error', uploadId, (data) => {
        console.log(`Error: ${data.error}%`)
      })
      Upload.addListener('cancelled', uploadId, (data) => {
        console.log(`Cancelled!`)
      })
      Upload.addListener('completed', uploadId, (data) => {
        console.log('Completed!')
      })
    }).catch((err) => {
      console.log('Upload error!', err)
    })
  }

Error: 
`Upload error! Error: NSInvalidArgumentException
    at createErrorFromErrorData (NativeModules.js:123)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:347)
    at MessageQueue.js:137
    at MessageQueue.__guard (MessageQueue.js:265)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
    at debuggerWorker.js:72`

**Comment by AlfredOdling** [comment]
@StevePotter Yes that is the behavior I would have wanted, thank you!

**Comment by waterstar** [comment]
Same issue, any solution.

**Comment by StevePotter** [comment]
@AlfredOdling @waterstar no solution yet, although I will be personally adding that functionality into the next release of the package.  @TSMMark and I work on it in our spare time so I can't promise an exact date.  I'm going to close this issue but you have my word that the problem will be fixed in the next release.

@AlfredOdling @waterstar what are you uploading?  Videos, photos, both?

**Comment by StevePotter** [comment]
@AlfredOdling @waterstar the library supports assets-library files now.

**Comment by AlfredOdling** [comment]
@StevePotter Awesome, good job.

**Comment by isaachinman** [comment]
@abhirajevolvier Does the code you posted work now that the codebase has been updated? I am running nearly identical code to you, and all my uploads are cancelling immediately with no useful error feedback:

    Cancelled! {id: "10", error: "cancelled", responseBody: null}

**Comment by AlfredOdling** [comment]
I have not tried the new code so I don’t know.

26 mars 2018 kl. 19:10 skrev Isaac Hinman <notifications@github.com<mailto:notifications@github.com>>:


@abhirajevolvier<https://github.com/abhirajevolvier> Does the code you posted work now that the codebase has been updated? I am running nearly identical code to you, and all my uploads are cancelling immediately with no useful error feedback:

Cancelled! {id: "10", error: "cancelled", responseBody: null}

**Comment by abhirajevolvier** [comment]
@AlfredOdling I didn't tried the latest code but have tried multipart file uploading and no issues found.

**Comment by isaachinman** [comment]
I am getting this error as well:

    Upload error:  Error: NSInvalidArgumentException
        at createErrorFromErrorData (NativeModules.js:123)
        at NativeModules.js:80
        at MessageQueue.__invokeCallback (MessageQueue.js:400)
        at MessageQueue.js:139
        at MessageQueue.__guardSafe (MessageQueue.js:316)
        at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:138)
        at debuggerWorker.js:72

When I try to upload this photo:

![test_image](https://user-images.githubusercontent.com/10575782/37976588-17e11e9a-31e2-11e8-80ef-aa6abe9c1faa.jpg)

This is on iOS as well. The URI looks like this:

    file:///Users/isaachinman/Library/Developer/CoreSimulator/Devices/CD3DC2CC-CE2F-4E4D-BABE-331B49C22BDF/data/Containers/Data/PluginKitPlugin/ECBC38E1-855C-4055-9134-3559858C6C18/tmp/test_image.jpg

@StevePotter Want to reopen this or should I open a new issue?

**Comment by ankits47b** [comment]
@abhirajevolvier 
Your file path does not contain "file:///"
so add "file:///    / User...... and so on
