### ISSUE TITLE
Unsupported scheme (Android)

### ISSUE THREAD

**Issue by buskerone** [Vydia/react-native-background-upload#57]
I got the error - only on Android - : Unsupported scheme: file:///storage/emulated/0/Android/data/com.nnn.android.client/files/Pictures/image-9ed429ce-5b06-4f04-816a-c278e5da33d4.jpg

v4.1.0
react-native-cli: 2.0.1
react-native: 0.51.0

`
const options = {
      url: url,
      path: path,
      method: 'PUT',
      headers: {
        JWT: openIdToken,
      },
      // Below are options only supported on Android
      notification: {
        enabled: true,
      },
    }
Upload.startUpload(options)
      .then(uploadId => {
        Upload.addListener('completed', uploadId, data => {
          resolve()
        })
      })
      .catch(e => {
        sendLog(`Cannot upload image ${e}`, true)
        reject(e)
      })`

Anyone with the same issue?

**Comment by buskerone** [comment]
If anyone has the same issue it's because of this:
https://github.com/gotev/android-upload-service/blob/80f425610ea2a12830c8e32804a3d6ae2928936f/uploadservice/src/main/java/net/gotev/uploadservice/schemehandlers/SchemeHandlerFactory.java

line: 23
`private SchemeHandlerFactory() {
        handlers.put("/", FileSchemeHandler.class);
        handlers.put("content://", ContentSchemeHandler.class);
}`

How to fix? shitty fix but it works-> Platform.OS === 'ios' ? path : path.replace('file://', ''),

**Comment by TSMMark** [comment]
Please check out the example app we have provided and see if that helps you 

https://github.com/Vydia/ReactNativeBackgroundUploadExample/blob/master/js/components/Upload.js#L90

```js
if (Platform.OS === 'android') {
  this.startUpload(Object.assign({ path }, options))
} else {
  this.startUpload(Object.assign({ path: uri }, options))
}
```

**Comment by StevePotter** [comment]
@buskerone if you want to add a PR, fixing the url to strip the file:// could be handled in the Java module or in the library (with a Platform check)
