### ISSUE TITLE
Cannot Read Property 'startUpload' of undefined 

### ISSUE THREAD

**Issue by harshsrivastavaglobussoft** [Vydia/react-native-background-upload#58]
![screenshot at jan 30 18-51-44](https://user-images.githubusercontent.com/24026483/35568349-ab6a94cc-05ee-11e8-8b26-8bebdf86a67f.png)

 Trying to upload a video with two more parameters 

Details:-
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-background-upload": "^4.1.0",

     uploadVideo =()=>{
         let formData = new FormData();
           formData.append("host_id", "79********");
           formData.append("file_type", 1);
           formData.append("hostfiles", {
                name: this.state.fileName,
                uri: this.state.videoFile.path,
           });

    const options = {
      url: "https://Demo******.com:6021/user/api/host/uploadfiles",
      path: this.state.videoFile.path,
      method: 'POST',
      field:formData,
      headers: {
        'Content-Type': 'multipart/form-data',
         'Accept': 'application/json'
      },
      type: 'multipart'
    };

    Upload.startUpload(options).then((uploadId) => {
       console.log('Upload started')
       Upload.addListener('progress', uploadId, (data) => {
         console.log(`Progress: ${data.progress}%`)
       })
       Upload.addListener('error', uploadId, (data) => {
         console.log(`Error: ${data.error}%`)
       })
       Upload.addListener('completed', uploadId, (data) => {
         console.log('Completed!')
       })
       }).catch((err) => {
          console.log('Upload error!', err)
      });
    }

**Comment by StevePotter** [comment]
Hey @harshsrivastavaglobussoft it looks like there is a problem importing.  Can you paste the whole file, or at least the relevant pieces with your import up top?

**Comment by StevePotter** [comment]
Package name is misspelled.  You have `'reiact-native-background-upload'` and it should be `'react-native-background-upload'`.

**Comment by superandrew213** [comment]
@harshsrivastavaglobussoft how did you get this to work with `formData`?

**Comment by harshsrivastavaglobussoft** [comment]
@superandrew213 it did not work with `formData` any idea how to add it in this case?

**Comment by superandrew213** [comment]
@harshsrivastavaglobussoft I have no idea what `field` is for and how you can use it with `type: 'multipart'`. It must be a string so it can't accept `formData`.

```
const options = {
  url: 'https://myservice.com/path/to/post',
  path: 'file://path/to/file/on/device',
  method: 'POST',
  field: 'uploaded_media',
  type: 'multipart'
}
```

@StevePotter can you give an example how you can use field?

**Comment by harshsrivastavaglobussoft** [comment]
@StevePotter I guess you need to convert the object for `field` to JSON String you can use `JSON.stringify()` for that. I am still searching a way to upload video for android
