### ISSUE TITLE
Fatal exception. Bad notification for startForeground.

### ISSUE THREAD

**Issue by dtuite** [Vydia/react-native-background-upload#59]
This exception occurs in SDK 27 (Android 8.1) but not in lower SDK versions.

```
Fatal Exception: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 groupKey=com.clamber vis=PRIVATE)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Turning off notifications prevents the exception from occurring.

```
    const options = {
      // ...
      notification: {
        // Required to prevent 
        enabled: false,
      },
    };
```

The issue appears to be fairly common and widely document for other libraries. I believe [this is the same issue on SO](https://stackoverflow.com/questions/47531742/startforeground-fail-after-upgrade-to-android-8-1).

I don't have a reproduction available but I believe there is one in [an issue on this other upload library](https://github.com/NativeScript/nativescript-background-http/issues/85#issuecomment-360156779)

**Comment by TSMMark** [comment]
Thanks for the report @dtuite. Do you think you could submit a PR?

**Comment by dtuite** [comment]
I just had a look at the Java files you have in here and honestly I doubt I can. I don't know any Java or anything about native android libraries really so it would probably take me weeks to learn and follow through all the docs. If I could see a simple way to modify `UploaderModule.java` to look more like that in the SO answer I linked to I'd do it but that doesn't seem to be the case.

**Comment by TSMMark** [comment]
@dtuite I talked with the team and we don't have the bandwidth to prioritize diagnosing and fixing this exception at the moment; however, if `notification: { enabled: false }` really does fix the issue, we would be happy to accept a PR that simply adds this clause to the documentation!

**Comment by dtuite** [comment]
Ready for review.

**Comment by TSMMark** [comment]
@watadarkstar Good idea! PRs welcome :)

**Comment by watadarkstar** [comment]
If I have some time I'll tackle this @TSMMark but no promises 🙏

**Comment by StevePotter** [comment]
@watadarkstar @TSMMark how about we turn off notifications by default?  We'd have to do a major version bump and release notes but it's a very easy fix.

**Comment by watadarkstar** [comment]
@StevePotter I'd prefer that they were on by default and disabled on APK 27 and greater automatically. Seems like a cleaner experience and probably still very little work (a one or two liner).

**Comment by peterent** [comment]
Using APK 28. After searching and searching I finally found this thread. I turned notification off. Now the app doesn't crash. Instead, it throws this error:
"Android Oreo requires a notification configuration for the service to run. https://developer.android.com/reference/android/content/Context.html#startForegroundService(android.content.Intent)"
