### ISSUE TITLE
Error "Unfortunately, `app` has stopped"

### ISSUE THREAD

**Issue by L-Yeiser** [Vydia/react-native-background-upload#64]
Adding `react-native-background-upload` to my project causes breaking issue in android. When the app opens a modal pops up with the error `Unfortunately, app has stopped`. I tried running the app on multiple different android phones including an android simulator. The crash is caused by the runtime error `Could not invoke WebSocketModule.connect at com.facebook.react.bridge.JavaMethodWrapper.invoke`

Here is the stack trace: 
![screen shot 2018-03-12 at 12 33 01 pm](https://user-images.githubusercontent.com/6750498/37305416-94a057e0-25f1-11e8-9544-41f9eedbbc06.png)

react-native version: 0.53.0
react-native-background-upload version: 4.4.0.

app/build.gradle
```
dependencies {
    compile project(':react-native-background-upload')
    compile project(':react-native-sensitive-info')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    compile project(':react-native-navigation')
    compile project(':mapbox-react-native-mapbox-gl')
}

// required by react-native-background-upload until React Native supports okhttp >= okhttp 3.5
configurations.all { resolutionStrategy.force 'com.squareup.okhttp3:okhttp:3.4.1' }
```

MainApplication.java
```
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new UploaderReactPackage(),
            new RNSensitiveInfoPackage(),
          new RCTMGLPackage()
        );
    }
```

settings.gradle
```
include ':react-native-background-upload'
project(':react-native-background-upload').projectDir = new File(settingsDir, '../node_modules/react-native-background-upload/android')
include ':react-native-sensitive-info'
project(':react-native-sensitive-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sensitive-info/android')

include ':app'

include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/android/app/')

include ':mapbox-react-native-mapbox-gl'
project(':mapbox-react-native-mapbox-gl').projectDir = new File(rootProject.projectDir, '../node_modules/@mapbox/react-native-mapbox-gl/android/rctmgl')
```

The `compileSDKVersion` is "26.0.1" and the `targetSDKVersion` is "26".

**Comment by isaachinman** [comment]
@StevePotter You should remove that from Step 2 in the [Android manual setup](https://github.com/Vydia/react-native-background-upload/blob/master/README.md#android) instructions. It's not clear this is _only_ for v3 and not for v4.

**Comment by StevePotter** [comment]
@isaachinman readme updated, now it's clear

**Comment by bcgilliom** [comment]
There still seems to be that step 2. Almost got me!
