### ISSUE TITLE
Upload error! Error: type should be string: raw or multipart. In case of Android as well iOS works good..

### ISSUE THREAD

**Issue by ankits47b** [Vydia/react-native-background-upload#65]
Upload error! Error: type should be string: raw or multipart.
    at createErrorFromErrorData (NativeModules.js:123)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:400)
    at MessageQueue.js:139
    at MessageQueue.__guardSafe (MessageQueue.js:316)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:138)
    at debuggerWorker.js:72

**Comment by TSMMark** [comment]
Hello, are you providing the option `type`? Allowed values are either `'raw'` or `'multipart'`. See usage in Readme: https://github.com/Vydia/react-native-background-upload#usage

**Comment by ankits47b** [comment]
I Resolve this issue passing [code]'raw' in type and my image is uploaded Thanks

**Comment by ankits47b** [comment]
Works for me passing 'raw' in type
