### ISSUE TITLE
Docs regarding linking are misleading

### ISSUE THREAD

**Issue by isaachinman** [Vydia/react-native-background-upload#66]
Found this project recently and was really looking forward to using it. I've encountered a _really_ weird issue though that has prevented me from doing so.

To anyone just opening this issue, I'm sure it will seem like a very common import mistake. However, it's not.

I did `yarn add react-native-background-upload`. Then I just copy/pasted the usage example straight into my application:

    import Upload from 'react-native-background-upload'

    const options = {
      url: 'https://myservice.com/path/to/post',
      path: 'file://path/to/file/on/device',
      method: 'POST',
      type: 'raw',
      headers: {
        'my-custom-header': 's3headervalueorwhateveryouneed'
      },
      // Below are options only supported on Android
      notification: {
        enabled: true
      }
    }

    console.log('What is Upload: ', Upload)

    Upload.startUpload(options).then((uploadId) => {
      console.log('Upload started')
      Upload.addListener('progress', uploadId, (data) => {
        console.log(`Progress: ${data.progress}%`)
      })
      Upload.addListener('error', uploadId, (data) => {
        console.log(`Error: ${data.error}%`)
      })
      Upload.addListener('cancelled', uploadId, (data) => {
        console.log(`Cancelled!`)
      })
      Upload.addListener('completed', uploadId, (data) => {
        // data includes responseCode: number and responseBody: Object
        console.log('Completed!')
      })
    }).catch((err) => {
      console.log('Upload error!', err)
    })

Here's what I see when this runs:

![screen shot 2018-03-26 at 17 48 14](https://user-images.githubusercontent.com/10575782/37917129-e52b8d6a-311d-11e8-8bd3-3a2d88c9abb6.png)

Really don't understand this. You can see the output of the console log directly before the function invocation, and `Upload` is clearly an object with several methods on it, `startUpload` being the first one.

This is probably a more general RN problem (?), but I'm not at all sure where to start. Any ideas?

**Comment by isaachinman** [comment]
Figured this out. The native module was indeed undefined, but for some reason it was not undefined until called. Some weird bridge thing. Here's why:

[The formatting of the main README](https://github.com/Vydia/react-native-background-upload/blob/master/README.md#manual-native-library-linking) makes it seems as though this library only requires linking if you're using RN <0.47. This section should use `##` in markdown to indicate it's not a subheader of the "Installation for React Native < 0.47" section.

Second, I noticed this project does not have a `podspec` and created one myself via `patch-package`.

If the maintainers think they would merge either of these two fixes (1. Docs fix, 2. podspec) please let me know and I will put together PR(s).

Thanks!

**Comment by TSMMark** [comment]
You are indeed correct the readme should not have that section as a subheader. PRs defintely welcome!

**Comment by StevePotter** [comment]
@isaachinman @TSMMark how about this update?  Does that clear up confusion?
https://github.com/Vydia/react-native-background-upload/pull/68

**Comment by StevePotter** [comment]
@isaachinman why does this package need a podspec or header search paths set?

**Comment by isaachinman** [comment]
> how about this update? Does that clear up confusion?

Yeah, looks great to me.

> why does this package need a podspec or header search paths set?

So that people using cocoapods can install this package as a dependency... The changes needed are very minimal, see [this commit](https://github.com/Wundershine/react-native-background-upload/commit/e34d94244c05af881ff81477bffe7a44c1909257) on my fork. If you're willing to merge this let me know and I'll create a separate issue.

**Comment by isaachinman** [comment]
@StevePotter Happy to merge the pods support at any time.

**Comment by sraka1** [comment]
@isaachinman how did you resolve the issue though (with this module being undefined at call-time)? I linked the module, cleaned and re-built in Xcode and still get this...
