### ISSUE TITLE
401 is calling "completed" event

### ISSUE THREAD

**Issue by isaachinman** [Vydia/react-native-background-upload#67]
Just a quick one: in setting up this project in my own app, I noticed that 401 server responses are still triggering the "completed" event. All 4xx responses should presumably call the "error" event, not "completed".

**Comment by isaachinman** [comment]
Update: it looks like probably all 4xx and 5xx errors are triggering the "completed" event. Not sure if this "completed" event is only supposed to be in reference to the clientside functionality, but I would expect it to throw into the "error" event for http error code responses.

**Comment by StevePotter** [comment]
@isaachinman yeah the completed event seems to be coming regardless of response code.

I would say we need two things.  The first is API documentation.  The second is a 'success' event that will not occur in the event of an error http response code.  @TSMMark what do you think of this proposal?

**Comment by TSMMark** [comment]
Sounds good

**Comment by isaachinman** [comment]
So this issue was closed, but I don't see a release containing any fix. What's the timeframe on this?

**Comment by shahchaitanya** [comment]
I'm facing still same issue. Any progress on this thread? @TSMMark @StevePotter

**Comment by StevePotter** [comment]
@shahchaitanya no progress, sorry.  Are you interested in making a PR?

**Comment by ZORenoAcct** [comment]
Hi @StevePotter I believe if this is a rest based client, any non-200 should throw an error event and not completed.

**Comment by dcurletti** [comment]
bump. agree that `4xx` and `5xx` responses shouldn't trigger `completed`.

**Comment by shahchaitanya** [comment]
Here i temporarily fixed solution. OnCompleted listener gives data which contains response code. I checked whether is it 4xx and 5xx or not.
