### ISSUE TITLE
[Help wanted] Convert to file:// path

### ISSUE THREAD

**Issue by SebT** [Vydia/react-native-background-upload#7]
Hi,

It is specified in the README that we can only upload files with a path starting with `file://`.

I'm using react-native-camera to record a video that I want to upload and the path returned starts with `assets-library://` on iOS. I've been searching but I haven't found any way to convert this path to a `file://` path.

I come from cordova and I used to call `resolveLocalFileSystemURL(assetLibraryFilePath)` to get the `file://` but I can't seem to find an equivalent in react-native :(

Any help please ?

**Comment by StevePotter** [comment]
Hey @SebT this currently isn't possible in our library.  It is possible in another one https://github.com/booxood/react-native-file-upload/blob/master/FileUpload.m#L78 but that library doesn't support many of the features this one does.

I want to support asset library files but as you can see from the code, it's a pretty major undertaking.  Please keep watching us and one of these days I'll implement it.  We actually need this for our own app.  Currently we use react-native-image-picker to convert videos to a file:// url, but it's compressed and asset-library is ideal

**Comment by SebT** [comment]
I feel like this is a problem for many react-native developers. There should be a react native library for file system manipulation that would provide utility functions to convert paths.

I don't know Objective-C and I'm not very familiar with the Android SDK so I won't be able to contribute to any react-native library before I learn these first. In the meantime I think I'll post an issue on a FS library to implement these utility method so that everybody can use them.
