### ISSUE TITLE
Error: expected x bytes but received y%

### ISSUE THREAD

**Issue by V3RT1AG0** [Vydia/react-native-background-upload#71]
Whenever I try to upload image to my Digital ocean spaces it starts uploading and then restarts again before reaching 100% and after one or two such attempts it throws me an error which looks something like this:
Error: expected 1433 bytes but received 1500%

I am not sure what is going wrong here

I am uploading the image using presigned url using following options

```
                const options = {
					url: data.url,
					path: uri,
					method: "PUT",
					type: "raw",
					field: "uploaded_media",
					headers: {
						"Content-Type": type,
						"x-amz-acl": "public-read"
					},
					notification: {
						enabled: true
					}
				};

```

**Comment by StevePotter** [comment]
@V3RT1AG0 that's really bizarre.  What is 'type' in 'Content-Type' header?  Does this happen on both platforms, or just Android or iOS?

**Comment by V3RT1AG0** [comment]
@StevePotter I think this is a issue with using content:// path of the image. When I use file:// uri it is uploading perfectly without any issue. I tried it on both AWS s3 and Digital Ocean Spaces. I was getting the same error. The content-type is image/jpeg btw

**Comment by sraka1** [comment]
Btw, I had the same issue (for the same reason - using content:// URIs on Android). RNs CameraRoll API returns these by default. I used https://github.com/Wraptime/react-native-get-real-path to get the real path... Also take note, that you need to provide the URI without file:// on Android...

Basically something like.
```
  async getPath (uri) {
    if (Platform.OS === 'ios') {
      return uri
    } else {
      // Android
      if (uri.startsWith('content://')) {
        try {
          uri = await RNGRP.getRealPathFromURI(uri)
        } catch (error) {
          console.log('Do something with error...')
        }
      }
      return uri.replace('file://', '')
    }
  }
```

**Comment by StevePotter** [comment]
@sraka1 would you be willing to make a PR that includes that functionality inside the package?
