### ISSUE TITLE
Path with spaces breaks upload

### ISSUE THREAD

**Issue by isaachinman** [Vydia/react-native-background-upload#72]
Hello, it's me again!

First, the "symptoms" of this bug are a bug themselves - it seems whenever `react-native-background-upload` hits a runtime error, it calls the "Cancelled" event instead of "Error", which provides absolutely no data about what just happened.

The main bug: paths with spaces in them do not work whatsoever. I'm looking into workarounds now and how to escape this in a way that the library can find the file, but am not having success so far. 

Here's an example of a pretty "dirty" URI that I would expect to work with this library, but currently is not:

    file:///Users/isaachinman/Library/Developer/CoreSimulator/Devices/336A9F2F-F5E7-4DD5-83BB-F40CBD15548D/data/Containers/Data/PluginKitPlugin/958086C1-0339-42F7-922A-7600B4B1C690/tmp/05 - february 2018 (myphotopack.com).jpg

**Update:** I was able to get this working with a simple `encodeURI`. Options:

1. Expect users to provide safe urls, don't encode for them. Provide some kind of helpful feedback instead of failing silently.

2. Encode path for users.

**Comment by StevePotter** [comment]
@isaachinman thanks for the report.  Can you give me steps to reproduce on the simulator?  We'd really appreciate some help on this.  Any way you can make a quick PR?

**Comment by isaachinman** [comment]
@StevePotter Passing any path with spaces in it will reproduce the issue.

Sure, I can make a PR, but first we'd have to decide how to proceed.

**Comment by StevePotter** [comment]
Good question.  If `encodeURI` fixes it, I would go that route.  But, I would be concerned that encodeURI could also break something.  So as long as thorough testing is done, I say we just fix it right.

**Comment by isaachinman** [comment]
What are you worried about it breaking? `encodeURI` is a built-in for this exact purpose, and if you call it on a URI that has already been encoded, it just returns the same value. So we should be able to process all URIs through `encodeURI` without any issues.

Do you maybe have a few example URIs from your own use cases we can compare?

**Comment by TSMMark** [comment]
> if you call it on a URI that has already been encoded, it just returns the same value

Does it?

```js
encodeURI(" ")
// => "%20"
encodeURI("%20")
// => "%2520"
```

**Comment by isaachinman** [comment]
@TSMMark You're completely right, my mistake. Not sure how I got that in my head but it seems `encodeURI` will encode whatever you pass it without any logic.

@StevePotter I think it would be entirely appropriate to leave this burden on users, but check against URIs containing spaces and throw a warning.

**Comment by TSMMark** [comment]
I agree the burden should be on the user to supply a valid URI. Checking specifically for spaces does seem a little too niche to me though. There are plenty of characters that are not acceptable in a valid URI, and there are characters that are only valid in certain parts of a URI.

Perhaps a simple documentation update is the best approach after all. Thoughts?

**Comment by isaachinman** [comment]
@TSMMark Sure, the proposal would be "check if URI is valid", not something as specific as checking for spaces.

The docs can be updated to reflect this, sure, but the real core issue here is this:

> First, the "symptoms" of this bug are a bug themselves - it seems whenever react-native-background-upload hits a runtime error, it calls the "Cancelled" event instead of "Error", which provides absolutely no data about what just happened.

I've seen this happen several times now in my use of this library - errors are simply swallowed. I have no idea where/why this is happening.

If I got an "unexpected character" error spit out at me with a stacktrace to the URI, this issue probably wouldn't have been opened in the first place.

Any ideas how to fix this? Can move this discussion to another issue if you want.

**Comment by TSMMark** [comment]
I opened #74 to close up the original issue here. Feel free to open one about

> First, the "symptoms" of this bug are a bug themselves - it seems whenever react-native-background-upload hits a runtime error, it calls the "Cancelled" event instead of "Error", which provides absolutely no data about what just happened.

**Comment by isaachinman** [comment]
Just ran into this again. I hit a bug when uploading from a WhatsApp-related directory, due to spaces:

> Error: /storage/emulated/0/WhatsApp/Media/WhatsApp%20Images/IMG-20180604-WA0002.jpg (No such file or directory)%

Here's what I'm doing prior to passing the URI to this lib:

    if (Platform.OS === 'android') {
      image.uri = image.uri.replace('file://', '')
    }

    image.uri = encodeURI(image.uri)

In the exact case above, if I _don't_ encode the URI and leave the spaces raw in the path, it _does_ work. No idea what's going on here but it's a very annoying issue.
