### ISSUE TITLE
iOS 'React/RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by watadarkstar** [Vydia/react-native-background-upload#75]
I get this error when I try to build on iOS

> node_modules/react-native-background-upload/ios/VydiaRNFileUploader.m:3:9: 'React/RCTEventEmitter.h' file not found

Any ideas?

**Comment by StevePotter** [comment]
@watadarkstar that's a compilation error where the compiler can't find the React Native headers.  It's almost definitely a problem with your setup or an old version of React Native.

I'm going to need some more information.  What version of RN and of this package are you using?  Are you using any other packages?

**Comment by watadarkstar** [comment]
@StevePotter 

I see. I use [Expo](https://expo.io) and recently upgraded my RN version, but I think this issue started once this library was added not after RN was upgraded. Though I believe you its something to do with RN headers not being found.

```
"expo": "^26.0.0",
"react": "16.3.0-alpha.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz",
```

Btw thanks for the quick reply, awesome!

**Comment by watadarkstar** [comment]
@StevePotter 

I think I solved the problem:

To use this library with Expo one must first detach (eject) the project and follow the normal `react-native link` instructions. Additionally on iOS there is a must to add a Header Search Path to other dependencies which are managed using Pods. To do so one has to add $(SRCROOT)/../../../ios/Pods/Headers/Public/** to Header Search Path in `VydiaRNFileUploader Group` module using XCode. As shown below:

![screen shot 2018-04-12 at 9 58 32 am](https://user-images.githubusercontent.com/3059371/38682051-27f5aa1e-3e38-11e8-92a7-1d711aecc0ff.png)

**Comment by TSMMark** [comment]
@watadarkstar So glad you got it sorted out! Your documentation PR looks good to me. I'll let @StevePotter merge it, and close this issue in the mean time.

**Comment by StevePotter** [comment]
@watadarkstar thanks for your effort and the PR to address this.  I've never tried to use this through Expo.  I wonder if something can be done to make it automatic.  Any ideas?

**Comment by watadarkstar** [comment]
@StevePotter yes you can make it automatic. From another project, this is what they say in their [instructions](https://github.com/Polidea/react-native-ble-plx#expo):

```
This can be further automated by a `git apply patch` executed as a `postinstall` script defined in `package.json`.
```

I wouldn't say this is the best approach and probably would be worth some more googling to see what others are doing.

**Comment by kdawgwilk** [comment]
This does not actually fix the issue because each time you run a `yarn install` the change to add the header search paths will be reset and need to happen again

**Comment by StevePotter** [comment]
@kdawgwilk any ideas on how to fix it?  I don't use Expo so I'm not any help here

**Comment by kdawgwilk** [comment]
I opened a PR #96 that fixed my issues with cocoapods but I am not using expo so not sure if it addresses that scenario
