### ISSUE TITLE
build.gradle issue

### ISSUE THREAD

**Issue by VaishaliHawaldar** [Vydia/react-native-background-upload#78]
In our project we are pointing to latest compileSdkVersion 27.0.0 as it is latest. But as the react-native-background is using 25 we are getting build issues. As we are using other packages too using latest sdk versions, we cant degrade to 25, could you please upgrade sdk version to latest sdk version.

**Comment by TSMMark** [comment]
Hi @VaishaliHawaldar, we'll try to look into this soon. In the mean time feel free to submit a PR, historically we usually review and merge within 1 business day

**Comment by StevePotter** [comment]
@VaishaliHawaldar you could also do this without upgrading the package by setting this in the `mobile/android/build.gradle`

```
// thanks to https://stackoverflow.com/questions/24494077/gradle-force-build-tools-version-on-third-party-libraries
ext {
    compileSdkVersion = 27
    buildToolsVersion = "27.0.3"
}
// set main properties in dependencies
subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
```

**Comment by VaishaliHawaldar** [comment]
Hi Marco,

Sorry for late reply. We have just upgraded our app version with 27.0 as
many packages support latest sdk versions. Now it is working perfectly
fine. There is no need to fix this issue.

Thanks for all the help provided.

**Comment by VaishaliHawaldar** [comment]
Hi Stephen,

Sorry for late reply. We have just upgraded our app version with 27.0 as
many packages support latest sdk versions. Now it is working perfectly
fine. There is no need to fix this issue.

Thanks for all the help provided

**Comment by TSMMark** [comment]
Thanks for looping back @VaishaliHawaldar!

**Comment by StevePotter** [comment]
@MarcoPortillo try my suggestion in your main gradle.  That has the benefit of fixing all libraries, not just this one
