### ISSUE TITLE
how can i pass list of images as input this library.

### ISSUE THREAD

**Issue by mahesh-vidhate** [Vydia/react-native-background-upload#79]
I want upload list images to the server, but using your library I can only pass single image at a time.
I can also call this library API multiple times using a loop or something. But the problem is when my app goes in background, it will only upload the current image which is in the upload process, it is not initiating further uploads.
So is there any way by which I can pass all list of images as input to your library and it will handle rest of all

**Comment by StevePotter** [comment]
Closing due to lack of response and no example
