### ISSUE TITLE
Android can't find file:///storage/emulated

### ISSUE THREAD

**Issue by SebT** [Vydia/react-native-background-upload#8]
Hi,

On android I have an error when trying to upload a file created with react-native-camera:
`Upload error! Error: Could not find file at path: file://storage/emulated/0/Movies/VID_20170202_094146.mp4 the path `

Any idea ?

**Comment by StevePotter** [comment]
Apparently this is a problem in the library, as it only supports files created in a certain way.  It would be great if you could create a sample app for me to test on

**Comment by SebT** [comment]
I'll create one when I have time. FYI the path was generated by a video taken with the plugin [https://github.com/lwansbrough/react-native-camera](react-native-camera).

**Comment by SebT** [comment]
Here's the gist for you to test : https://gist.github.com/SebT/2a87a7c902842a812ef47775cc28bc32

**Comment by StevePotter** [comment]
Thanks @SebT I'll check it out

**Comment by ox-michaelradionov** [comment]
This error also appeared for me and I also use react-native-camera, but I was able to get rid of it by truncating `file://` protocol from the beginning of the file path.

For example if you have:

```
file:///storage/emulated/0/Movies/VID_20170202_094146.mp4
```

it should become

```
/storage/emulated/0/Movies/VID_20170202_094146.mp4
```

**Comment by SebT** [comment]
Hmm. I'll test this. But the README says :

> The easist way to tell is that the url should always start with 'file://'

So I guess we should patch the code to accept this kind of path when it starts with 'file://'

**Comment by TSMMark** [comment]
@ox-michaelradionov I noticed there are three consecutive slashes in your URI (2 in the protocol, 1 leading in the path). if you kill the leading slash and only use the slashes in the `file://` protocol `file://storage/emulated/0/Movies/VID_20170202_094146.mp4` do you get positive results?

**Comment by ox-michaelradionov** [comment]
@TSMMark , no, it fails with two slashes as well (`file://`)

**Comment by akotlov** [comment]
I also had the same error when I was using a path generated by react-native-camera (on android)-"file:///storage/emulated/0/Pictures/VID_20170227_203358.mp4".

I truncated the path to "storage/emulated/0/Pictures/VID_20170227_203358.mp4" and the error was gone.

let path = "file:///storage/emulated/0/Pictures/VID_20170227_203358.mp4"
path.substring(path.indexOf('s'))

**Comment by StevePotter** [comment]
@ox-michaelradionov and @akotlov I'll have to look into this further.  So @akotlov you're saying we should remove the file:// protocol from the front?

**Comment by akotlov** [comment]
@StevePotter I think so.I looked at "Android upload service" library source and seems like that what the library author decided to do.
![screenshot_20170301-145509](https://cloud.githubusercontent.com/assets/901548/23523051/1683558a-ff3a-11e6-8526-2f8ef7cab999.png)

**Comment by StevePotter** [comment]
@akotlov did you end up with a workaround?  Should we have the library drop the 'file://' prefix in Android?
