### ISSUE TITLE
Update android-upload-service to version 3.4 to fix notification crashes

### ISSUE THREAD

**Issue by jasennett** [Vydia/react-native-background-upload#87]
`android-upload-service` added notification channel support for Android O in the [version 3.4 release](https://github.com/gotev/android-upload-service/releases/tag/3.4).  Updating to this version and passing in a channel id to the `UploadNotificationConfig` `setNotificationChannelId()` setter should fix the crash when enabling notifications on Android O.  Could support a `channelId` property alongside the `enabled` property in the `notification` request options or just pass in a default that would be pretty sure to be unique.

**Comment by jasennett** [comment]
Pull request #86 is already updating the version of the library, so the only additional work would be to configure the channel id for the `UploadNotificationConfig` object

**Comment by albinhubsch** [comment]
Pull request #95 will solve this

**Comment by StevePotter** [comment]
Done and published!
