### ISSUE TITLE
No throttling of upload progress

### ISSUE THREAD

**Issue by StevePotter** [Vydia/react-native-background-upload#9]
During upload, many many progress events can be updated, and this can result in a choppy UI.  This could be bypassed with some effort on the app side, but really the progress events should be only emitted periodically.

I propose a property progressReportInterval:number, which is the minimum difference in progress % from the previous event.  So if you set this to 1, you will only get updates at 1%, 2%, 3%, etc.  Set it to 10 and you'll get 10%, 20%...  It should accept a range from 0 (disabled) to 100, although I see no practical use for it above 10.

Anyone have ideas here?

**Comment by TSMMark** [comment]
I'm not convinced percentage-based customization is the solution. for large files, it makes sense, but what about small files? For example, uploading a small image should only take a few seconds (for easy math, let's say 2 seconds), if you have progress events configured to 1%, you'll get 50 progress events triggered per second. It seems like perhaps in addition to a percent-based config, there should be a millisecond-based config, with a reasonable default of 20ms (5-per second) or something.

**Comment by StevePotter** [comment]
Mark I like your idea.  Easy to implement.

**Comment by sraka1** [comment]
@StevePotter why was this closed?

**Comment by StefanoCremona** [comment]
Do the latest releases implement something similar?
I have to upload very large files (1GB) and the percentage moves to 1% just after few minutes.
So the user doesn't have the evidence something is happening.
