### ISSUE TITLE
Unknown error when upload 2mins video from camera.

### ISSUE THREAD

**Issue by perfectAlways1028** [Vydia/react-native-background-upload#93]
Device : iPad
Package Version 4.4.0

I got "Unknown Error" when I upload over 2mins video from camera.
It is working fine when I upload smaller video like 30s.

Let me know if you have any solution
Thanks

**Comment by L-Yeiser** [comment]
Related to https://github.com/Vydia/react-native-background-upload/issues/85

**Comment by L-Yeiser** [comment]
Also related to https://github.com/Vydia/react-native-background-upload/issues/53. Curiously if you run the example app and switch `media` to `any` in the `react-native-image-crop-picker` config and try to upload the same video do you see the error?

**Comment by mbarreyro** [comment]
Any solution? I'm having this exact same error for videos of more than 1 minute.
