### ISSUE TITLE
TImeout Error.

### ISSUE THREAD

**Issue by baxri** [Vydia/react-native-background-upload#99]
## USSUE MAY BE A BUG

Hi, I am trying to upload on the server 800mb data. the server is digitalocean droplet with php 7.1.

when it starts the upload and reaches 10%, the percentage is resetting and starts from zero (0%), and it restarts upload few times after 10%, after a while, I am getting the timeout error.

Has anyone have such problem on a big data?

**Comment by dannyvassallo** [comment]
Can you provide some more information? What OS? Does it happen on both? We don't usually see any issues based on file size alone. Do you have an actual error or stack trace or is it simply a timeout? @baxri

**Comment by baxri** [comment]
Thanks for your response @dannyvassallo 

I am testing on android OS 7.0, code is looks like this:

```javascript
BackgroundUpload.startUpload(options).then((uploadId) => {
            console.log('Upload started')
            BackgroundUpload.addListener('progress', uploadId, (data) => {
                console.log(`Progress: ${data.progress}%`)
            })
            BackgroundUpload.addListener('error', uploadId, (data) => {
                console.log(`Error: ${data.error}%`)
                alert(`Error: ${data.error}%`);
            })
            BackgroundUpload.addListener('cancelled', uploadId, (data) => {
                console.log(`Cancelled!`)
                alert("Canceled!");
            })
            BackgroundUpload.addListener('completed', uploadId, (data) => {
                // data includes responseCode: number and responseBody: Object
                console.log('Completed!')
                console.log(data)
                alert("Upload Completed");
            })
        }).catch((err) => {
            alert('Upload error!', err);
            console.log('Upload error!', err)
        })
```

and it throws second listener error ```alert(`Error: ${data.error}%`);```

The library is not limited to upload big data? what is max size I can upload?

**Comment by dannyvassallo** [comment]
@baxri are you able to upload the same file from a web browser to your server? typically the file size and timeout is governed by your host/server. The background uploader itself shouldn't time out.

**Comment by baxri** [comment]
@dannyvassallo thanks for your attention :) I figured out everything it was a server problem, there was some limitation. I gonna to close this issue.

**Comment by TSMMark** [comment]
@baxri glad you were able to figure it out and thanks for looping back to close out the issue! Thanks @dannyvassallo
